name: Docker Image for Planetary Annihilation image on GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: obiwantoby
          password: ${{ ssecrets.GHCR_PAT }}
      - uses: actions/checkout@v4
      - name: Build and push image
        run: |
          docker build . ghcr.io/obiwantoby/pa-dedicated-server:latest
          docker push ghcr.io/obiwantoby/pa-dedicated-server:latest